[tool.poetry]
name = "cacheables"
version = "0.1.1"
description = ""
authors = ["Thom Lane <thom.e.lane@gmail.com>"]
readme = "README.md"
repository = "https://github.com/thomelane/cacheables"

[tool.poetry.dependencies]
python = "^3.11"
loguru = "^0.7.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
